apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinity-api
  namespace: vodacom-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infinity-api
  template:
    metadata:
      labels:
        app: infinity-api
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      imagePullSecrets:
        - name: regsecret-fanclash
      containers:
        - name: infinity-api
          image: fanclashdevelopers/infinity-api:v1.11.2
          env:
            - name: "APP_ENV"
              value: "production"
            - name: "NODE_ENV"
              value: "production"
            - name: "APP_NAME"
              value: "MTN Soccer Fantasy League"
            - name: "PUBLIC_PORT"
              value: "8000"
            - name: "DCB_HOST"
              value: "http://10.107.244.112:5000"
            - name: "GAME_ENTRIES_HOST"
              value: "https://10.0.34.98:5000"
            - name: "USER_DATA_HOST"
              value: "10.0.224.51:5000"
            - name: "VOUCHER_VAULT_HOST"
              value: "http://10.103.97.116:5000"
            - name: "AUTOLOGIN_HOST"
              value: "http://10.100.59.96:5000"
            - name: "SMS_HOST"
              value: "0.0.0.0:5000"
            - name: "CORS_DOMAIN"
              value: "http://localhost:8080"
            - name: "FANCLASH_HOST"
              value: "https://penrosedigital.co.za"
            - name: "PGHOST"
              value: "database-fanclash-staging-za.postgres.database.azure.com"
            - name: "PGDATABASE"
              value: "infinity_api"
            - name: "PGUSER"
              value: "PenroseAdmin@database-fanclash-staging-za"
            - name: "PGPASSWORD"
              value: "PenDevClashers101!"
            - name: "PGPORT"
              value: "5432"
            - name: "SESSION_KEYS"
              value: "EsgoYxPavvBYcVBAZN,ADZJJmRbAQMaCWdkGQ,QTuywTPVDYVsJKjdUh"
            - name: "STATSD_HOST"
              value: "http://10.103.233.87"
            - name: "STATSD_PORT"
              value: "8125"
            - name: "STATSD_PREFIX"
              value: "infinity_api"
            - name: "MODULES"
              value: "login,dcb,gameEntries,userData,autoLogin"
            - name: "USER_DATA_DECRYPTION_HOST"
              value: "10.0.114.241"
