apiVersion: v1
kind: Service
metadata:
  name: service-fanclash-user-middleware
  namespace: vodacom-staging
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: service-fanclash-user-middleware
