apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-game-entries
  namespace: vodacom-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-game-entries
  template:
    metadata:
      labels:
        app: service-game-entries
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      imagePullSecrets:
        - name: regsecret-fanclash
      containers:
        - name: service-game-entries
          image: fanclashdevelopers/service.game-entries:v1.1.3
          env:
            - name: "APP_ENV"
              value: "production"
            - name: "ADMIN_PORT"
              value: "8085"
            - name: "ADMIN_NAMESPACE"
              value: "game-entries"
            - name: "GRPC_PORT"
              value: "5015"
            - name: "APP_TIMEZONE"
              value: "Africa/Johannesburg"
            - name: "PGHOST"
              value: "database-fanclash-staging-za.postgres.database.azure.com"
            - name: "PGDATABASE"
              value: "game_entries"
            - name: "PGUSER"
              value: "PenroseAdmin@database-fanclash-staging-za"
            - name: "PGPASSWORD"
              value: "PenDevClashers101!"
            - name: "PGPORT"
              value: "5432"
            - name: "GAME_DATA_HOST"
              value: "10.0.38.92:5000"
            - name: "GAME_STATS_HOST"
              value: "10.0.182.5:5000"
            - name: "SMS_HOST"
              value: "192.168.192.143:31069"
            - name: "VOUCHER_SECRET"
              value: "secret"
            - name: "VOUCHER_VAULT_HOST"
              value: "192.168.192.143:30522"
            - name: "USER_DATA_HOST"
              value: "10.0.224.51:5000"
            - name: "AIRTIME_HOST"
              value: "'23'"
            - name: "RUNNER_UP_PRIZE_REF"
              value: "'22'"
            - name: "FIRST_PRIZE_TYPE"
              value: "Voucher"
            - name: "RUNNER_UP_PRIZE_TYPE"
              value: "Voucher"
            - name: "FIRST_PRIZE_AMOUNT"
              value: "2.50"
            - name: "RUNNER_PRIZE_AMOUNT"
              value: "2.50"
            - name: "POOL_SIZE"
              value: "10"
            - name: "SEND_SMS"
              value: "'false'"
            - name: "STATSD_HOST"
              value: "192.168.192.252"
            - name: "STATSD_PORT"
              value: "8125"
            - name: "STATSD_PREFIX"
              value: "game_entries"
            - name: "PAGINATION_LIMIT"
              value: "5"
            - name: "MAX_PLAYERS_RESULTS"
              value: "10"
            - name: "SET_WINNERS_JOB"
              value: "'21 9 * * *'"
            - name: "AWARD_VOUCHERS_JOB"
              value: "'48 1 * * *'"
            - name: "SEND_VOUCHERS_JOB"
              value: "'49 1 * * *'"
