apiVersion: v1
kind: Service
metadata:
  name: service-game-stats
  namespace: vodacom-staging
spec:
  type: ClusterIP
  ports:
    - name: application
      port: 80
      targetPort: 8087
    - name: grpc-server
      port: 5000
      targetPort: 5003
  selector:
    app: service-game-stats
