apiVersion: v1
kind: Service
metadata:
  name: service-wap-gateway-middleware
  namespace: utils
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: service-wap-gateway-middleware
