apiVersion: v1
kind: Service
metadata:
  name: fanclash-vodacom-sa-web
  namespace: vodacom-staging
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: fanclash-vodacom-sa-web
