apiVersion: v1
kind: Service
metadata:
  name: service-user-data
  namespace: vodacom-staging
spec:
  type: ClusterIP
  ports:
    - name: application
      port: 80
      targetPort: 8081
    - name: grpc-server
      port: 5000
      targetPort: 5006
  selector:
    app: service-user-data
